use gpui::actions;

actions!(
    crux,
    [
        NewTab,
        CloseTab,
        ForceCloseTab,
        NextTab,
        PrevTab,
        SelectTab1,
        SelectTab2,
        SelectTab3,
        SelectTab4,
        SelectTab5,
        SelectTab6,
        SelectTab7,
        SelectTab8,
        SelectTab9,
        SplitRight,
        SplitDown,
        WindowSplitRight,
        WindowSplitDown,
        FocusNextPane,
        FocusPrevPane,
        ZoomPane,
        PrevPrompt,
        NextPrompt,
    ]
);
